/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-08-02 02:21:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.html.taglib.ui.input_005fdate;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.liferay.exportimport.kernel.staging.LayoutStagingUtil;
import com.liferay.exportimport.kernel.staging.StagingUtil;
import com.liferay.layout.seo.kernel.LayoutSEOLink;
import com.liferay.layout.seo.kernel.LayoutSEOLinkManager;
import com.liferay.layout.seo.kernel.LayoutSEOLinkManagerUtil;
import com.liferay.petra.string.CharPool;
import com.liferay.petra.string.StringBundler;
import com.liferay.petra.string.StringPool;
import com.liferay.portal.kernel.bean.BeanParamUtil;
import com.liferay.portal.kernel.bean.BeanPropertiesUtil;
import com.liferay.portal.kernel.configuration.Filter;
import com.liferay.portal.kernel.cookies.CookiesManagerUtil;
import com.liferay.portal.kernel.dao.search.DisplayTerms;
import com.liferay.portal.kernel.dao.search.ResultRowSplitter;
import com.liferay.portal.kernel.dao.search.RowChecker;
import com.liferay.portal.kernel.dao.search.RowMover;
import com.liferay.portal.kernel.dao.search.SearchContainer;
import com.liferay.portal.kernel.exception.LocalizedException;
import com.liferay.portal.kernel.exception.NoSuchLayoutException;
import com.liferay.portal.kernel.json.JSONArray;
import com.liferay.portal.kernel.json.JSONFactoryUtil;
import com.liferay.portal.kernel.json.JSONObject;
import com.liferay.portal.kernel.language.LanguageUtil;
import com.liferay.portal.kernel.language.LanguageWrapper;
import com.liferay.portal.kernel.language.UnicodeLanguageUtil;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.log.LogUtil;
import com.liferay.portal.kernel.model.*;
import com.liferay.portal.kernel.model.impl.*;
import com.liferay.portal.kernel.model.impl.VirtualLayout;
import com.liferay.portal.kernel.portlet.InvokerPortlet;
import com.liferay.portal.kernel.portlet.LiferayHeaderRequest;
import com.liferay.portal.kernel.portlet.LiferayHeaderResponse;
import com.liferay.portal.kernel.portlet.LiferayPortletMode;
import com.liferay.portal.kernel.portlet.LiferayPortletURL;
import com.liferay.portal.kernel.portlet.LiferayRenderRequest;
import com.liferay.portal.kernel.portlet.LiferayRenderResponse;
import com.liferay.portal.kernel.portlet.LiferayWindowState;
import com.liferay.portal.kernel.portlet.PortletConfigFactoryUtil;
import com.liferay.portal.kernel.portlet.PortletInstanceFactoryUtil;
import com.liferay.portal.kernel.portlet.PortletPreferencesFactoryUtil;
import com.liferay.portal.kernel.portlet.PortletProvider;
import com.liferay.portal.kernel.portlet.PortletProviderUtil;
import com.liferay.portal.kernel.portlet.PortletSetupUtil;
import com.liferay.portal.kernel.portlet.PortletURLFactoryUtil;
import com.liferay.portal.kernel.portlet.PortletURLUtil;
import com.liferay.portal.kernel.portletdisplaytemplate.PortletDisplayTemplateManagerUtil;
import com.liferay.portal.kernel.security.auth.AuthTokenUtil;
import com.liferay.portal.kernel.security.auth.PrincipalException;
import com.liferay.portal.kernel.security.permission.ActionKeys;
import com.liferay.portal.kernel.security.permission.ResourceActionsUtil;
import com.liferay.portal.kernel.service.*;
import com.liferay.portal.kernel.service.permission.GroupPermissionUtil;
import com.liferay.portal.kernel.service.permission.LayoutPermissionUtil;
import com.liferay.portal.kernel.service.permission.PortletPermissionUtil;
import com.liferay.portal.kernel.service.permission.RolePermissionUtil;
import com.liferay.portal.kernel.servlet.BufferCacheServletResponse;
import com.liferay.portal.kernel.servlet.MultiSessionMessages;
import com.liferay.portal.kernel.servlet.PortalMessages;
import com.liferay.portal.kernel.servlet.PortalWebResourceConstants;
import com.liferay.portal.kernel.servlet.PortalWebResourcesUtil;
import com.liferay.portal.kernel.servlet.ServletContextPool;
import com.liferay.portal.kernel.servlet.SessionErrors;
import com.liferay.portal.kernel.servlet.SessionMessages;
import com.liferay.portal.kernel.servlet.taglib.ui.MenuItem;
import com.liferay.portal.kernel.util.ArrayUtil;
import com.liferay.portal.kernel.util.CalendarFactoryUtil;
import com.liferay.portal.kernel.util.Constants;
import com.liferay.portal.kernel.util.ContentTypes;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.FastDateFormatConstants;
import com.liferay.portal.kernel.util.FastDateFormatFactoryUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.HashMapBuilder;
import com.liferay.portal.kernel.util.HtmlParserUtil;
import com.liferay.portal.kernel.util.HtmlUtil;
import com.liferay.portal.kernel.util.Http;
import com.liferay.portal.kernel.util.HttpComponentsUtil;
import com.liferay.portal.kernel.util.IntegerWrapper;
import com.liferay.portal.kernel.util.JavaConstants;
import com.liferay.portal.kernel.util.KeyValuePair;
import com.liferay.portal.kernel.util.ListUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ParamUtil;
import com.liferay.portal.kernel.util.Portal;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.PortletKeys;
import com.liferay.portal.kernel.util.PrefsPropsUtil;
import com.liferay.portal.kernel.util.PropsKeys;
import com.liferay.portal.kernel.util.ReleaseInfo;
import com.liferay.portal.kernel.util.ServerDetector;
import com.liferay.portal.kernel.util.SessionClicks;
import com.liferay.portal.kernel.util.SetUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.TextFormatter;
import com.liferay.portal.kernel.util.Time;
import com.liferay.portal.kernel.util.TimeZoneUtil;
import com.liferay.portal.kernel.util.URLCodec;
import com.liferay.portal.kernel.util.UnicodeFormatter;
import com.liferay.portal.kernel.util.UnicodeProperties;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.util.WebKeys;
import com.liferay.portal.kernel.workflow.WorkflowConstants;
import com.liferay.portal.model.impl.*;
import com.liferay.portal.security.sso.SSOUtil;
import com.liferay.portal.service.*;
import com.liferay.portal.servlet.BrowserSnifferUtil;
import com.liferay.portal.struts.Definition;
import com.liferay.portal.struts.StrutsUtil;
import com.liferay.portal.struts.TilesUtil;
import com.liferay.portal.util.PropsUtil;
import com.liferay.portal.util.PropsValues;
import com.liferay.portal.util.ShutdownUtil;
import com.liferay.portlet.HeaderRequestFactory;
import com.liferay.portlet.HeaderResponseFactory;
import com.liferay.portlet.LiferayPortletUtil;
import com.liferay.portlet.RenderParametersPool;
import com.liferay.portlet.RenderRequestFactory;
import com.liferay.portlet.RenderResponseFactory;
import com.liferay.portlet.configuration.kernel.util.PortletConfigurationUtil;
import com.liferay.portlet.usersadmin.util.UsersAdminUtil;
import com.liferay.sites.kernel.util.Sites;
import com.liferay.taglib.search.ResultRow;
import com.liferay.taglib.search.SearchEntry;
import com.liferay.taglib.search.TextSearchEntry;
import com.liferay.taglib.util.OutputTag;
import java.text.DateFormat;
import java.text.Format;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.ResourceBundle;
import java.util.Set;
import java.util.TimeZone;
import java.util.TreeSet;
import javax.portlet.MimeResponse;
import javax.portlet.MutableRenderParameters;
import javax.portlet.PortletConfig;
import javax.portlet.PortletContext;
import javax.portlet.PortletException;
import javax.portlet.PortletMode;
import javax.portlet.PortletPreferences;
import javax.portlet.PortletRequest;
import javax.portlet.PortletResponse;
import javax.portlet.PortletURL;
import javax.portlet.UnavailableException;
import javax.portlet.WindowState;
import com.liferay.portal.kernel.servlet.MultiSessionErrors;
import com.liferay.portal.kernel.util.DateFormatFactoryUtil;
import com.liferay.taglib.aui.AUIUtil;
import com.liferay.taglib.util.InlineUtil;
import com.liferay.taglib.util.TagResourceBundleUtil;

public final class page_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


private static final String _SIMPLE_DATE_FORMAT_PATTERN_HTML5 = "yyyy-MM-dd";

private static final String _MASK_YMD = "%Y/%m/%d";

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(11);
    _jspx_dependants.put("/WEB-INF/tld/liferay-portlet_2_0.tld", Long.valueOf(1718225656000L));
    _jspx_dependants.put("/html/taglib/init.jsp", Long.valueOf(1710321269000L));
    _jspx_dependants.put("/WEB-INF/tld/liferay-ui.tld", Long.valueOf(1718225697000L));
    _jspx_dependants.put("/html/common/init.jsp", Long.valueOf(1712363247000L));
    _jspx_dependants.put("/html/taglib/init-ext.jsp", Long.valueOf(1710321210000L));
    _jspx_dependants.put("/WEB-INF/tld/c.tld", Long.valueOf(1710321210000L));
    _jspx_dependants.put("/WEB-INF/tld/liferay-portlet-ext.tld", Long.valueOf(1710321270000L));
    _jspx_dependants.put("/html/common/init-ext.jsp", Long.valueOf(1710321210000L));
    _jspx_dependants.put("/WEB-INF/tld/liferay-aui.tld", Long.valueOf(1712363247000L));
    _jspx_dependants.put("/WEB-INF/tld/liferay-util.tld", Long.valueOf(1710321270000L));
    _jspx_dependants.put("/WEB-INF/tld/liferay-theme.tld", Long.valueOf(1710321270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(8);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.liferay.portal.kernel.model.impl");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.liferay.portal.kernel.model");
    _jspx_imports_packages.add("com.liferay.portal.model.impl");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.liferay.portal.kernel.service");
    _jspx_imports_packages.add("com.liferay.portal.service");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(160);
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.PrefsPropsUtil");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.ContentTypes");
    _jspx_imports_classes.add("com.liferay.portlet.RenderRequestFactory");
    _jspx_imports_classes.add("java.util.Arrays");
    _jspx_imports_classes.add("java.text.Format");
    _jspx_imports_classes.add("com.liferay.portal.kernel.dao.search.RowMover");
    _jspx_imports_classes.add("com.liferay.portal.kernel.servlet.PortalMessages");
    _jspx_imports_classes.add("com.liferay.portlet.usersadmin.util.UsersAdminUtil");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.WebKeys");
    _jspx_imports_classes.add("com.liferay.portal.kernel.workflow.WorkflowConstants");
    _jspx_imports_classes.add("com.liferay.portal.kernel.service.permission.RolePermissionUtil");
    _jspx_imports_classes.add("com.liferay.portal.util.PropsUtil");
    _jspx_imports_classes.add("com.liferay.portal.kernel.security.auth.PrincipalException");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("com.liferay.taglib.util.OutputTag");
    _jspx_imports_classes.add("com.liferay.portal.kernel.servlet.MultiSessionErrors");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.PropsKeys");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.GetterUtil");
    _jspx_imports_classes.add("com.liferay.portal.kernel.portlet.LiferayWindowState");
    _jspx_imports_classes.add("javax.portlet.PortletContext");
    _jspx_imports_classes.add("com.liferay.portal.kernel.log.LogFactoryUtil");
    _jspx_imports_classes.add("com.liferay.portal.kernel.servlet.ServletContextPool");
    _jspx_imports_classes.add("com.liferay.portal.kernel.portlet.InvokerPortlet");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.SessionClicks");
    _jspx_imports_classes.add("java.util.Set");
    _jspx_imports_classes.add("com.liferay.taglib.util.TagResourceBundleUtil");
    _jspx_imports_classes.add("com.liferay.portal.util.PropsValues");
    _jspx_imports_classes.add("javax.portlet.PortletConfig");
    _jspx_imports_classes.add("com.liferay.portal.kernel.language.LanguageUtil");
    _jspx_imports_classes.add("com.liferay.portal.kernel.portlet.LiferayRenderResponse");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.JavaConstants");
    _jspx_imports_classes.add("com.liferay.taglib.search.TextSearchEntry");
    _jspx_imports_classes.add("com.liferay.portlet.HeaderResponseFactory");
    _jspx_imports_classes.add("com.liferay.portlet.LiferayPortletUtil");
    _jspx_imports_classes.add("com.liferay.portal.kernel.portlet.PortletProviderUtil");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.HashMapBuilder");
    _jspx_imports_classes.add("com.liferay.petra.string.StringPool");
    _jspx_imports_classes.add("com.liferay.portal.kernel.portlet.PortletURLUtil");
    _jspx_imports_classes.add("com.liferay.portal.kernel.portlet.LiferayPortletURL");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.URLCodec");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.DateFormatFactoryUtil");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("javax.portlet.MimeResponse");
    _jspx_imports_classes.add("com.liferay.portal.kernel.portlet.PortletPreferencesFactoryUtil");
    _jspx_imports_classes.add("java.text.NumberFormat");
    _jspx_imports_classes.add("java.util.TreeSet");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.FastDateFormatConstants");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("com.liferay.portal.kernel.servlet.SessionMessages");
    _jspx_imports_classes.add("java.util.ResourceBundle");
    _jspx_imports_classes.add("com.liferay.portal.kernel.service.permission.PortletPermissionUtil");
    _jspx_imports_classes.add("com.liferay.portal.kernel.security.permission.ActionKeys");
    _jspx_imports_classes.add("com.liferay.portal.kernel.dao.search.SearchContainer");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.TimeZoneUtil");
    _jspx_imports_classes.add("com.liferay.portal.kernel.portlet.LiferayHeaderRequest");
    _jspx_imports_classes.add("com.liferay.portal.kernel.servlet.PortalWebResourcesUtil");
    _jspx_imports_classes.add("java.util.LinkedHashSet");
    _jspx_imports_classes.add("com.liferay.portal.kernel.bean.BeanPropertiesUtil");
    _jspx_imports_classes.add("com.liferay.portal.kernel.portlet.PortletConfigFactoryUtil");
    _jspx_imports_classes.add("com.liferay.portal.kernel.servlet.SessionErrors");
    _jspx_imports_classes.add("com.liferay.portlet.RenderParametersPool");
    _jspx_imports_classes.add("javax.portlet.MutableRenderParameters");
    _jspx_imports_classes.add("com.liferay.portal.kernel.cookies.CookiesManagerUtil");
    _jspx_imports_classes.add("com.liferay.portal.kernel.portletdisplaytemplate.PortletDisplayTemplateManagerUtil");
    _jspx_imports_classes.add("javax.portlet.PortletPreferences");
    _jspx_imports_classes.add("com.liferay.layout.seo.kernel.LayoutSEOLinkManager");
    _jspx_imports_classes.add("com.liferay.taglib.search.SearchEntry");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.Portal");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.HttpComponentsUtil");
    _jspx_imports_classes.add("com.liferay.portal.kernel.json.JSONObject");
    _jspx_imports_classes.add("com.liferay.portal.servlet.BrowserSnifferUtil");
    _jspx_imports_classes.add("com.liferay.taglib.aui.AUIUtil");
    _jspx_imports_classes.add("com.liferay.portal.kernel.dao.search.ResultRowSplitter");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.ArrayUtil");
    _jspx_imports_classes.add("com.liferay.layout.seo.kernel.LayoutSEOLinkManagerUtil");
    _jspx_imports_classes.add("com.liferay.exportimport.kernel.staging.StagingUtil");
    _jspx_imports_classes.add("com.liferay.petra.string.CharPool");
    _jspx_imports_classes.add("com.liferay.portal.kernel.security.permission.ResourceActionsUtil");
    _jspx_imports_classes.add("com.liferay.portal.kernel.json.JSONArray");
    _jspx_imports_classes.add("com.liferay.portal.kernel.service.permission.LayoutPermissionUtil");
    _jspx_imports_classes.add("com.liferay.portal.kernel.configuration.Filter");
    _jspx_imports_classes.add("com.liferay.portal.security.sso.SSOUtil");
    _jspx_imports_classes.add("com.liferay.petra.string.StringBundler");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.HtmlUtil");
    _jspx_imports_classes.add("javax.portlet.PortletURL");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.TextFormatter");
    _jspx_imports_classes.add("com.liferay.portal.kernel.servlet.taglib.ui.MenuItem");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("com.liferay.portal.kernel.exception.LocalizedException");
    _jspx_imports_classes.add("com.liferay.portal.kernel.bean.BeanParamUtil");
    _jspx_imports_classes.add("com.liferay.portal.util.ShutdownUtil");
    _jspx_imports_classes.add("com.liferay.portal.kernel.log.LogUtil");
    _jspx_imports_classes.add("com.liferay.portal.kernel.exception.NoSuchLayoutException");
    _jspx_imports_classes.add("com.liferay.portal.kernel.servlet.MultiSessionMessages");
    _jspx_imports_classes.add("java.util.Locale");
    _jspx_imports_classes.add("com.liferay.portlet.HeaderRequestFactory");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.Constants");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.ReleaseInfo");
    _jspx_imports_classes.add("com.liferay.portal.struts.StrutsUtil");
    _jspx_imports_classes.add("com.liferay.portal.kernel.dao.search.DisplayTerms");
    _jspx_imports_classes.add("java.text.DateFormat");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.LocaleUtil");
    _jspx_imports_classes.add("javax.portlet.UnavailableException");
    _jspx_imports_classes.add("com.liferay.portal.kernel.servlet.PortalWebResourceConstants");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.Time");
    _jspx_imports_classes.add("java.util.TimeZone");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.PortalUtil");
    _jspx_imports_classes.add("javax.portlet.PortletResponse");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.Validator");
    _jspx_imports_classes.add("com.liferay.portal.kernel.language.UnicodeLanguageUtil");
    _jspx_imports_classes.add("com.liferay.exportimport.kernel.staging.LayoutStagingUtil");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.StringUtil");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.UnicodeProperties");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.PortletKeys");
    _jspx_imports_classes.add("com.liferay.taglib.search.ResultRow");
    _jspx_imports_classes.add("java.util.Objects");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.ServerDetector");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.LocalizationUtil");
    _jspx_imports_classes.add("javax.portlet.WindowState");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.ListUtil");
    _jspx_imports_classes.add("com.liferay.portlet.RenderResponseFactory");
    _jspx_imports_classes.add("com.liferay.layout.seo.kernel.LayoutSEOLink");
    _jspx_imports_classes.add("com.liferay.portal.kernel.language.LanguageWrapper");
    _jspx_imports_classes.add("com.liferay.portal.kernel.security.auth.AuthTokenUtil");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.HtmlParserUtil");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.UnicodeFormatter");
    _jspx_imports_classes.add("com.liferay.portal.kernel.portlet.LiferayRenderRequest");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.SetUtil");
    _jspx_imports_classes.add("com.liferay.portal.struts.Definition");
    _jspx_imports_classes.add("com.liferay.portal.kernel.model.impl.VirtualLayout");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.IntegerWrapper");
    _jspx_imports_classes.add("com.liferay.portal.kernel.log.Log");
    _jspx_imports_classes.add("javax.portlet.PortletMode");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.KeyValuePair");
    _jspx_imports_classes.add("java.util.HashSet");
    _jspx_imports_classes.add("com.liferay.portal.kernel.portlet.PortletProvider");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.FastDateFormatFactoryUtil");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.CalendarFactoryUtil");
    _jspx_imports_classes.add("com.liferay.portal.kernel.dao.search.RowChecker");
    _jspx_imports_classes.add("javax.portlet.PortletRequest");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.ParamUtil");
    _jspx_imports_classes.add("com.liferay.portal.kernel.portlet.PortletInstanceFactoryUtil");
    _jspx_imports_classes.add("com.liferay.portal.kernel.portlet.PortletSetupUtil");
    _jspx_imports_classes.add("com.liferay.portal.struts.TilesUtil");
    _jspx_imports_classes.add("com.liferay.sites.kernel.util.Sites");
    _jspx_imports_classes.add("com.liferay.portal.kernel.json.JSONFactoryUtil");
    _jspx_imports_classes.add("com.liferay.portal.kernel.service.permission.GroupPermissionUtil");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.Http");
    _jspx_imports_classes.add("com.liferay.portlet.configuration.kernel.util.PortletConfigurationUtil");
    _jspx_imports_classes.add("com.liferay.portal.kernel.portlet.LiferayPortletMode");
    _jspx_imports_classes.add("com.liferay.portal.kernel.servlet.BufferCacheServletResponse");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.DateUtil");
    _jspx_imports_classes.add("com.liferay.portal.kernel.portlet.LiferayHeaderResponse");
    _jspx_imports_classes.add("java.util.Collections");
    _jspx_imports_classes.add("com.liferay.portal.kernel.portlet.PortletURLFactoryUtil");
    _jspx_imports_classes.add("javax.portlet.PortletException");
    _jspx_imports_classes.add("com.liferay.taglib.util.InlineUtil");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      //  liferay-theme:defineObjects
      com.liferay.taglib.theme.DefineObjectsTag _jspx_th_liferay_002dtheme_005fdefineObjects_005f0 = new com.liferay.taglib.theme.DefineObjectsTag();
      _jsp_getInstanceManager().newInstance(_jspx_th_liferay_002dtheme_005fdefineObjects_005f0);
      try {
        _jspx_th_liferay_002dtheme_005fdefineObjects_005f0.setPageContext(_jspx_page_context);
        _jspx_th_liferay_002dtheme_005fdefineObjects_005f0.setParent(null);
        int _jspx_eval_liferay_002dtheme_005fdefineObjects_005f0 = _jspx_th_liferay_002dtheme_005fdefineObjects_005f0.doStartTag();
        if (_jspx_th_liferay_002dtheme_005fdefineObjects_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_liferay_002dtheme_005fdefineObjects_005f0, _jsp_getInstanceManager(), false);
      }
      com.liferay.portal.kernel.theme.ThemeDisplay themeDisplay = null;
      com.liferay.portal.kernel.model.Company company = null;
      com.liferay.portal.kernel.model.User user = null;
      com.liferay.portal.kernel.model.User realUser = null;
      com.liferay.portal.kernel.model.Contact contact = null;
      com.liferay.portal.kernel.model.Layout layout = null;
      java.util.List layouts = null;
      java.lang.Long plid = null;
      com.liferay.portal.kernel.model.LayoutTypePortlet layoutTypePortlet = null;
      java.lang.Long scopeGroupId = null;
      com.liferay.portal.kernel.security.permission.PermissionChecker permissionChecker = null;
      java.util.Locale locale = null;
      java.util.TimeZone timeZone = null;
      com.liferay.portal.kernel.model.Theme theme = null;
      com.liferay.portal.kernel.model.ColorScheme colorScheme = null;
      com.liferay.portal.kernel.theme.PortletDisplay portletDisplay = null;
      java.lang.Long portletGroupId = null;
      themeDisplay = (com.liferay.portal.kernel.theme.ThemeDisplay) _jspx_page_context.findAttribute("themeDisplay");
      company = (com.liferay.portal.kernel.model.Company) _jspx_page_context.findAttribute("company");
      user = (com.liferay.portal.kernel.model.User) _jspx_page_context.findAttribute("user");
      realUser = (com.liferay.portal.kernel.model.User) _jspx_page_context.findAttribute("realUser");
      contact = (com.liferay.portal.kernel.model.Contact) _jspx_page_context.findAttribute("contact");
      layout = (com.liferay.portal.kernel.model.Layout) _jspx_page_context.findAttribute("layout");
      layouts = (java.util.List) _jspx_page_context.findAttribute("layouts");
      plid = (java.lang.Long) _jspx_page_context.findAttribute("plid");
      layoutTypePortlet = (com.liferay.portal.kernel.model.LayoutTypePortlet) _jspx_page_context.findAttribute("layoutTypePortlet");
      scopeGroupId = (java.lang.Long) _jspx_page_context.findAttribute("scopeGroupId");
      permissionChecker = (com.liferay.portal.kernel.security.permission.PermissionChecker) _jspx_page_context.findAttribute("permissionChecker");
      locale = (java.util.Locale) _jspx_page_context.findAttribute("locale");
      timeZone = (java.util.TimeZone) _jspx_page_context.findAttribute("timeZone");
      theme = (com.liferay.portal.kernel.model.Theme) _jspx_page_context.findAttribute("theme");
      colorScheme = (com.liferay.portal.kernel.model.ColorScheme) _jspx_page_context.findAttribute("colorScheme");
      portletDisplay = (com.liferay.portal.kernel.theme.PortletDisplay) _jspx_page_context.findAttribute("portletDisplay");
      portletGroupId = (java.lang.Long) _jspx_page_context.findAttribute("portletGroupId");
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      //  portlet:defineObjects
      com.liferay.taglib.portlet.DefineObjectsTag _jspx_th_portlet_005fdefineObjects_005f0 = new com.liferay.taglib.portlet.DefineObjectsTag();
      _jsp_getInstanceManager().newInstance(_jspx_th_portlet_005fdefineObjects_005f0);
      try {
        _jspx_th_portlet_005fdefineObjects_005f0.setPageContext(_jspx_page_context);
        _jspx_th_portlet_005fdefineObjects_005f0.setParent(null);
        int _jspx_eval_portlet_005fdefineObjects_005f0 = _jspx_th_portlet_005fdefineObjects_005f0.doStartTag();
        if (_jspx_th_portlet_005fdefineObjects_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_portlet_005fdefineObjects_005f0, _jsp_getInstanceManager(), false);
      }
      javax.portlet.ActionRequest actionRequest = null;
      javax.portlet.ActionResponse actionResponse = null;
      javax.portlet.EventRequest eventRequest = null;
      javax.portlet.EventResponse eventResponse = null;
      com.liferay.portal.kernel.portlet.LiferayPortletRequest liferayPortletRequest = null;
      com.liferay.portal.kernel.portlet.LiferayPortletResponse liferayPortletResponse = null;
      javax.portlet.PortletConfig portletConfig = null;
      java.lang.String portletName = null;
      javax.portlet.PortletPreferences portletPreferences = null;
      java.util.Map portletPreferencesValues = null;
      javax.portlet.PortletSession portletSession = null;
      java.util.Map portletSessionScope = null;
      javax.portlet.RenderRequest renderRequest = null;
      javax.portlet.RenderResponse renderResponse = null;
      javax.portlet.ResourceRequest resourceRequest = null;
      javax.portlet.ResourceResponse resourceResponse = null;
      actionRequest = (javax.portlet.ActionRequest) _jspx_page_context.findAttribute("actionRequest");
      actionResponse = (javax.portlet.ActionResponse) _jspx_page_context.findAttribute("actionResponse");
      eventRequest = (javax.portlet.EventRequest) _jspx_page_context.findAttribute("eventRequest");
      eventResponse = (javax.portlet.EventResponse) _jspx_page_context.findAttribute("eventResponse");
      liferayPortletRequest = (com.liferay.portal.kernel.portlet.LiferayPortletRequest) _jspx_page_context.findAttribute("liferayPortletRequest");
      liferayPortletResponse = (com.liferay.portal.kernel.portlet.LiferayPortletResponse) _jspx_page_context.findAttribute("liferayPortletResponse");
      portletConfig = (javax.portlet.PortletConfig) _jspx_page_context.findAttribute("portletConfig");
      portletName = (java.lang.String) _jspx_page_context.findAttribute("portletName");
      portletPreferences = (javax.portlet.PortletPreferences) _jspx_page_context.findAttribute("portletPreferences");
      portletPreferencesValues = (java.util.Map) _jspx_page_context.findAttribute("portletPreferencesValues");
      portletSession = (javax.portlet.PortletSession) _jspx_page_context.findAttribute("portletSession");
      portletSessionScope = (java.util.Map) _jspx_page_context.findAttribute("portletSessionScope");
      renderRequest = (javax.portlet.RenderRequest) _jspx_page_context.findAttribute("renderRequest");
      renderResponse = (javax.portlet.RenderResponse) _jspx_page_context.findAttribute("renderResponse");
      resourceRequest = (javax.portlet.ResourceRequest) _jspx_page_context.findAttribute("resourceRequest");
      resourceResponse = (javax.portlet.ResourceResponse) _jspx_page_context.findAttribute("resourceResponse");
      out.write('\n');
      out.write('\n');

PortletRequest portletRequest = (PortletRequest)request.getAttribute(JavaConstants.JAVAX_PORTLET_REQUEST);

PortletResponse portletResponse = (PortletResponse)request.getAttribute(JavaConstants.JAVAX_PORTLET_RESPONSE);

String namespace = AUIUtil.getNamespace(portletRequest, portletResponse);

if (Validator.isNull(namespace)) {
	namespace = AUIUtil.getNamespace(request);
}

String currentURL = null;

if ((portletRequest != null) && (portletResponse != null)) {
	PortletURL currentURLObj = PortletURLUtil.getCurrent(PortalUtil.getLiferayPortletRequest(portletRequest), PortalUtil.getLiferayPortletResponse(portletResponse));

	currentURL = currentURLObj.toString();
}
else {
	currentURL = PortalUtil.getCurrentURL(request);
}

ResourceBundle resourceBundle = TagResourceBundleUtil.getResourceBundle(request, locale);

pageContext.setAttribute("resourceBundle", resourceBundle);

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');

String randomNamespace = PortalUtil.generateRandomKey(request, "taglib_ui_input_date_page") + StringPool.UNDERLINE;

if (!GetterUtil.getBoolean((String)request.getAttribute("liferay-ui:input-date:useNamespace"), true)) {
	namespace = StringPool.BLANK;
}

String autoComplete = GetterUtil.getString((String)request.getAttribute("liferay-ui:input-date:autoComplete"));
String cssClass = GetterUtil.getString((String)request.getAttribute("liferay-ui:input-date:cssClass"));
String dateTogglerCheckboxLabel = GetterUtil.getString((String)request.getAttribute("liferay-ui:input-date:dateTogglerCheckboxLabel"), "disable");
boolean disabled = GetterUtil.getBoolean((String)request.getAttribute("liferay-ui:input-date:disabled"));
String dayParam = GetterUtil.getString((String)request.getAttribute("liferay-ui:input-date:dayParam"));
int dayValue = GetterUtil.getInteger((String)request.getAttribute("liferay-ui:input-date:dayValue"));
int firstDayOfWeek = GetterUtil.getInteger((String)request.getAttribute("liferay-ui:input-date:firstDayOfWeek"));
Date firstEnabledDate = GetterUtil.getDate(request.getAttribute("liferay-ui:input-date:firstEnabledDate"), DateFormatFactoryUtil.getDate(locale), null);
String formName = GetterUtil.getString((String)request.getAttribute("liferay-ui:input-date:formName"));
Date lastEnabledDate = GetterUtil.getDate(request.getAttribute("liferay-ui:input-date:lastEnabledDate"), DateFormatFactoryUtil.getDate(locale), null);
String monthParam = GetterUtil.getString((String)request.getAttribute("liferay-ui:input-date:monthParam"));
int monthValue = GetterUtil.getInteger((String)request.getAttribute("liferay-ui:input-date:monthValue"));
String name = GetterUtil.getString((String)request.getAttribute("liferay-ui:input-date:name"));
boolean nullable = GetterUtil.getBoolean((String)request.getAttribute("liferay-ui:input-date:nullable"));
boolean required = GetterUtil.getBoolean((String)request.getAttribute("liferay-ui:input-date:required"));
boolean showDisableCheckbox = GetterUtil.getBoolean((String)request.getAttribute("liferay-ui:input-date:showDisableCheckbox"));
String yearParam = GetterUtil.getString((String)request.getAttribute("liferay-ui:input-date:yearParam"));
int yearValue = GetterUtil.getInteger((String)request.getAttribute("liferay-ui:input-date:yearValue"));

String dayParamId = namespace + HtmlUtil.getAUICompatibleId(dayParam);
String monthParamId = namespace + HtmlUtil.getAUICompatibleId(monthParam);
String nameId = namespace + HtmlUtil.getAUICompatibleId(name);
String yearParamId = namespace + HtmlUtil.getAUICompatibleId(yearParam);

Calendar calendar = null;

if (required && (yearValue == 0) && (monthValue == -1) && (dayValue == 0)) {
	calendar = CalendarFactoryUtil.getCalendar(timeZone);

	dayValue = calendar.get(Calendar.DAY_OF_MONTH);
	monthValue = calendar.get(Calendar.MONTH);
	yearValue = calendar.get(Calendar.YEAR);
}
else {
	calendar = CalendarFactoryUtil.getCalendar(yearValue, monthValue, dayValue);
}

String mask = _MASK_YMD;
String simpleDateFormatPattern = _SIMPLE_DATE_FORMAT_PATTERN_HTML5;

if (!BrowserSnifferUtil.isMobile(request)) {
	DateFormat shortDateFormat = DateFormat.getDateInstance(DateFormat.SHORT, locale);

	SimpleDateFormat shortDateFormatSimpleDateFormat = (SimpleDateFormat)shortDateFormat;

	simpleDateFormatPattern = shortDateFormatSimpleDateFormat.toPattern();

	simpleDateFormatPattern = simpleDateFormatPattern.replaceAll("yyyy", "y");
	simpleDateFormatPattern = simpleDateFormatPattern.replaceAll("yy", "y");
	simpleDateFormatPattern = simpleDateFormatPattern.replaceAll("MM", "M");
	simpleDateFormatPattern = simpleDateFormatPattern.replaceAll("dd", "d");

	simpleDateFormatPattern = simpleDateFormatPattern.replaceAll("y", "yyyy");
	simpleDateFormatPattern = simpleDateFormatPattern.replaceAll("M", "MM");
	simpleDateFormatPattern = simpleDateFormatPattern.replaceAll("d", "dd");

	mask = simpleDateFormatPattern;

	// Replace single quotes to prevent the string from breaking when passing
	// into the A.DatePicker mask. This is used for the zh_HK locale which
	// returns the format yyyy'å¹´'MM'æ'dd'æ¥'. See LPS-191923.

	mask = mask.replaceAll("'", "");

	mask = mask.replaceAll("yyyy", "%Y");
	mask = mask.replaceAll("MM", "%m");
	mask = mask.replaceAll("dd", "%d");
}

String dayAbbreviation = LanguageUtil.get(resourceBundle, "day-abbreviation");
String monthAbbreviation = LanguageUtil.get(resourceBundle, "month-abbreviation");
String yearAbbreviation = LanguageUtil.get(resourceBundle, "year-abbreviation");

String[] dateAbbreviations = {"M", "d", "y"};
String[] localizedDateAbbreviations = {monthAbbreviation, dayAbbreviation, yearAbbreviation};

String placeholderValue = StringUtil.replace(simpleDateFormatPattern, dateAbbreviations, localizedDateAbbreviations);

boolean nullDate = false;

if (nullable && !required && (dayValue == 0) && (monthValue == -1) && (yearValue == 0)) {
	nullDate = true;
}

String dateString = null;

Format format = FastDateFormatFactoryUtil.getSimpleDateFormat(simpleDateFormatPattern, locale);

if (nullable && nullDate) {
	dateString = StringPool.BLANK;
}
else {
	dateString = format.format(calendar.getTime());
}

      out.write("\n");
      out.write("\n");
      out.write("<span class=\"lfr-input-date\" id=\"");
      out.print( randomNamespace );
      out.write("displayDate\">\n");
      out.write("	");
      out.write('\n');
      out.write('	');
      out.write('	');
if (
 BrowserSnifferUtil.isMobile(request) ) {
      out.write("\n");
      out.write("			<input ");
      out.print( Validator.isNotNull(autoComplete) ? "autocomplete=\"" + autoComplete + "\"" : StringPool.BLANK );
      out.write(" class=\"form-control ");
      out.print( cssClass );
      out.write('"');
      out.write(' ');
      out.print( disabled ? "disabled=\"disabled\"" : "" );
      out.write(" id=\"");
      out.print( nameId );
      out.write("\" name=\"");
      out.print( namespace + HtmlUtil.escapeAttribute(name) );
      out.write("\" type=\"date\" value=\"");
      out.print( dateString );
      out.write("\" />\n");
      out.write("		");
      out.write('\n');
      out.write('	');
      out.write('	');
}
else {
      out.write("\n");
      out.write("			");
      out.write("\n");
      out.write("				");
if (
 Validator.isNotNull(autoComplete) ) {
      out.write("\n");
      out.write("					");
      //  aui:input
      com.liferay.taglib.aui.InputTag _jspx_th_aui_005finput_005f0 = new com.liferay.taglib.aui.InputTag();
      _jsp_getInstanceManager().newInstance(_jspx_th_aui_005finput_005f0);
      try {
        _jspx_th_aui_005finput_005f0.setPageContext(_jspx_page_context);
        _jspx_th_aui_005finput_005f0.setParent(null);
        // /html/taglib/ui/input_date/page.jsp(121,5) null
        _jspx_th_aui_005finput_005f0.setDynamicAttribute(null, "autocomplete",  autoComplete );
        // /html/taglib/ui/input_date/page.jsp(121,5) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f0.setCssClass( cssClass );
        // /html/taglib/ui/input_date/page.jsp(121,5) name = disabled type = boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f0.setDisabled( disabled );
        // /html/taglib/ui/input_date/page.jsp(121,5) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f0.setId( HtmlUtil.getAUICompatibleId(name) );
        // /html/taglib/ui/input_date/page.jsp(121,5) name = label type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f0.setLabel("");
        // /html/taglib/ui/input_date/page.jsp(121,5) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f0.setName( name );
        // /html/taglib/ui/input_date/page.jsp(121,5) name = placeholder type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f0.setPlaceholder( StringUtil.toLowerCase(placeholderValue) );
        // /html/taglib/ui/input_date/page.jsp(121,5) name = required type = boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f0.setRequired( required );
        // /html/taglib/ui/input_date/page.jsp(121,5) name = title type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f0.setTitle("");
        // /html/taglib/ui/input_date/page.jsp(121,5) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f0.setType("text");
        // /html/taglib/ui/input_date/page.jsp(121,5) name = useNamespace type = boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f0.setUseNamespace( !StringPool.BLANK.equals(namespace) );
        // /html/taglib/ui/input_date/page.jsp(121,5) name = value type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f0.setValue( dateString );
        // /html/taglib/ui/input_date/page.jsp(121,5) name = wrappedField type = boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f0.setWrappedField( true );
        int _jspx_eval_aui_005finput_005f0 = _jspx_th_aui_005finput_005f0.doStartTag();
        if (_jspx_eval_aui_005finput_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          out.write("\n");
          out.write("						");
          //  aui:validator
          com.liferay.taglib.aui.ValidatorTagImpl _jspx_th_aui_005fvalidator_005f0 = new com.liferay.taglib.aui.ValidatorTagImpl();
          _jsp_getInstanceManager().newInstance(_jspx_th_aui_005fvalidator_005f0);
          try {
            _jspx_th_aui_005fvalidator_005f0.setPageContext(_jspx_page_context);
            _jspx_th_aui_005fvalidator_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_aui_005finput_005f0);
            // /html/taglib/ui/input_date/page.jsp(122,6) name = errorMessage type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_aui_005fvalidator_005f0.setErrorMessage("please-enter-a-valid-date");
            // /html/taglib/ui/input_date/page.jsp(122,6) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_aui_005fvalidator_005f0.setName("custom");
            int _jspx_eval_aui_005fvalidator_005f0 = _jspx_th_aui_005fvalidator_005f0.doStartTag();
            if (_jspx_eval_aui_005fvalidator_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
              if (_jspx_eval_aui_005fvalidator_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_aui_005fvalidator_005f0);
              }
              do {
                out.write("\n");
                out.write("							function(val) {\n");
                out.write("								const dateValidation = AUI().use('aui-datatype-date-parse').Parsers.date('");
                out.print( mask );
                out.write("', val);\n");
                out.write("\n");
                out.write("								if (!dateValidation) {\n");
                out.write("									let parentNode = A.one('#");
                out.print( nameId );
                out.write("')._node.parentElement;\n");
                out.write("\n");
                out.write("									let feedbackElement = parentNode.querySelector('.form-feedback-item');\n");
                out.write("\n");
                out.write("									if (feedbackElement) {\n");
                out.write("										parentNode.removeChild(feedbackElement);\n");
                out.write("									}\n");
                out.write("								}\n");
                out.write("\n");
                out.write("								return dateValidation;\n");
                out.write("							}\n");
                out.write("						");
                int evalDoAfterBody = _jspx_th_aui_005fvalidator_005f0.doAfterBody();
                if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                  break;
              } while (true);
              if (_jspx_eval_aui_005fvalidator_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                out = _jspx_page_context.popBody();
              }
            }
            if (_jspx_th_aui_005fvalidator_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
              return;
            }
          } finally {
            org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_aui_005fvalidator_005f0, _jsp_getInstanceManager(), false);
          }
          out.write("\n");
          out.write("					");
        }
        if (_jspx_th_aui_005finput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_aui_005finput_005f0, _jsp_getInstanceManager(), false);
      }
      out.write("\n");
      out.write("				");
      out.write("\n");
      out.write("				");
}
else {
      out.write("\n");
      out.write("					");
      //  aui:input
      com.liferay.taglib.aui.InputTag _jspx_th_aui_005finput_005f1 = new com.liferay.taglib.aui.InputTag();
      _jsp_getInstanceManager().newInstance(_jspx_th_aui_005finput_005f1);
      try {
        _jspx_th_aui_005finput_005f1.setPageContext(_jspx_page_context);
        _jspx_th_aui_005finput_005f1.setParent(null);
        // /html/taglib/ui/input_date/page.jsp(142,5) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f1.setCssClass( cssClass );
        // /html/taglib/ui/input_date/page.jsp(142,5) name = disabled type = boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f1.setDisabled( disabled );
        // /html/taglib/ui/input_date/page.jsp(142,5) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f1.setId( HtmlUtil.getAUICompatibleId(name) );
        // /html/taglib/ui/input_date/page.jsp(142,5) name = label type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f1.setLabel("");
        // /html/taglib/ui/input_date/page.jsp(142,5) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f1.setName( name );
        // /html/taglib/ui/input_date/page.jsp(142,5) name = placeholder type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f1.setPlaceholder( StringUtil.toLowerCase(placeholderValue) );
        // /html/taglib/ui/input_date/page.jsp(142,5) name = required type = boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f1.setRequired( required );
        // /html/taglib/ui/input_date/page.jsp(142,5) name = title type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f1.setTitle("");
        // /html/taglib/ui/input_date/page.jsp(142,5) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f1.setType("text");
        // /html/taglib/ui/input_date/page.jsp(142,5) name = useNamespace type = boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f1.setUseNamespace( !StringPool.BLANK.equals(namespace) );
        // /html/taglib/ui/input_date/page.jsp(142,5) name = value type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f1.setValue( dateString );
        // /html/taglib/ui/input_date/page.jsp(142,5) name = wrappedField type = boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f1.setWrappedField( true );
        int _jspx_eval_aui_005finput_005f1 = _jspx_th_aui_005finput_005f1.doStartTag();
        if (_jspx_eval_aui_005finput_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          out.write("\n");
          out.write("						");
          //  aui:validator
          com.liferay.taglib.aui.ValidatorTagImpl _jspx_th_aui_005fvalidator_005f1 = new com.liferay.taglib.aui.ValidatorTagImpl();
          _jsp_getInstanceManager().newInstance(_jspx_th_aui_005fvalidator_005f1);
          try {
            _jspx_th_aui_005fvalidator_005f1.setPageContext(_jspx_page_context);
            _jspx_th_aui_005fvalidator_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_aui_005finput_005f1);
            // /html/taglib/ui/input_date/page.jsp(143,6) name = errorMessage type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_aui_005fvalidator_005f1.setErrorMessage("please-enter-a-valid-date");
            // /html/taglib/ui/input_date/page.jsp(143,6) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_aui_005fvalidator_005f1.setName("custom");
            int _jspx_eval_aui_005fvalidator_005f1 = _jspx_th_aui_005fvalidator_005f1.doStartTag();
            if (_jspx_eval_aui_005fvalidator_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
              if (_jspx_eval_aui_005fvalidator_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_aui_005fvalidator_005f1);
              }
              do {
                out.write("\n");
                out.write("							function(val) {\n");
                out.write("								const dateValidation = AUI().use('aui-datatype-date-parse').Parsers.date('");
                out.print( mask );
                out.write("', val);\n");
                out.write("\n");
                out.write("								if (!dateValidation) {\n");
                out.write("									let parentNode = A.one('#");
                out.print( nameId );
                out.write("')._node.parentElement;\n");
                out.write("\n");
                out.write("									let feedbackElement = parentNode.querySelector('.form-feedback-item');\n");
                out.write("\n");
                out.write("									if (feedbackElement) {\n");
                out.write("										parentNode.removeChild(feedbackElement);\n");
                out.write("									}\n");
                out.write("								}\n");
                out.write("								return dateValidation;\n");
                out.write("							}\n");
                out.write("						");
                int evalDoAfterBody = _jspx_th_aui_005fvalidator_005f1.doAfterBody();
                if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                  break;
              } while (true);
              if (_jspx_eval_aui_005fvalidator_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                out = _jspx_page_context.popBody();
              }
            }
            if (_jspx_th_aui_005fvalidator_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
              return;
            }
          } finally {
            org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_aui_005fvalidator_005f1, _jsp_getInstanceManager(), false);
          }
          out.write("\n");
          out.write("					");
        }
        if (_jspx_th_aui_005finput_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_aui_005finput_005f1, _jsp_getInstanceManager(), false);
      }
      out.write("\n");
      out.write("				");
      out.write("\n");
      out.write("			");
}
      out.write('\n');
      out.write('	');
      out.write('	');
      out.write('\n');
      out.write('	');
}
      out.write("\n");
      out.write("\n");
      out.write("	<input ");
      out.print( disabled ? "disabled=\"disabled\"" : "" );
      out.write(" id=\"");
      out.print( dayParamId );
      out.write("\" name=\"");
      out.print( namespace + HtmlUtil.escapeAttribute(dayParam) );
      out.write("\" type=\"hidden\" value=\"");
      out.print( dayValue );
      out.write("\" />\n");
      out.write("	<input ");
      out.print( disabled ? "disabled=\"disabled\"" : "" );
      out.write(" id=\"");
      out.print( monthParamId );
      out.write("\" name=\"");
      out.print( namespace + HtmlUtil.escapeAttribute(monthParam) );
      out.write("\" type=\"hidden\" value=\"");
      out.print( monthValue );
      out.write("\" />\n");
      out.write("	<input ");
      out.print( disabled ? "disabled=\"disabled\"" : "" );
      out.write(" id=\"");
      out.print( yearParamId );
      out.write("\" name=\"");
      out.print( namespace + HtmlUtil.escapeAttribute(yearParam) );
      out.write("\" type=\"hidden\" value=\"");
      out.print( yearValue );
      out.write("\" />\n");
      out.write("</span>\n");
      out.write("\n");
if (
 nullable && !required && showDisableCheckbox ) {
      out.write('\n');
      out.write('\n');
      out.write('	');

	String dateTogglerCheckboxName = TextFormatter.format(dateTogglerCheckboxLabel, TextFormatter.M);
	
      out.write('\n');
      out.write('\n');
      out.write('	');
      //  aui:input
      com.liferay.taglib.aui.InputTag _jspx_th_aui_005finput_005f2 = new com.liferay.taglib.aui.InputTag();
      _jsp_getInstanceManager().newInstance(_jspx_th_aui_005finput_005f2);
      try {
        _jspx_th_aui_005finput_005f2.setPageContext(_jspx_page_context);
        _jspx_th_aui_005finput_005f2.setParent(null);
        // /html/taglib/ui/input_date/page.jsp(176,1) name = label type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f2.setLabel( dateTogglerCheckboxLabel );
        // /html/taglib/ui/input_date/page.jsp(176,1) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f2.setName( randomNamespace + dateTogglerCheckboxName );
        // /html/taglib/ui/input_date/page.jsp(176,1) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f2.setType("checkbox");
        // /html/taglib/ui/input_date/page.jsp(176,1) name = value type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005finput_005f2.setValue( disabled );
        int _jspx_eval_aui_005finput_005f2 = _jspx_th_aui_005finput_005f2.doStartTag();
        if (_jspx_th_aui_005finput_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_aui_005finput_005f2, _jsp_getInstanceManager(), false);
      }
      out.write('\n');
      out.write('\n');
      out.write('	');
      //  aui:script
      com.liferay.taglib.aui.ScriptTag _jspx_th_aui_005fscript_005f0 = new com.liferay.taglib.aui.ScriptTag();
      _jsp_getInstanceManager().newInstance(_jspx_th_aui_005fscript_005f0);
      try {
        _jspx_th_aui_005fscript_005f0.setPageContext(_jspx_page_context);
        _jspx_th_aui_005fscript_005f0.setParent(null);
        int _jspx_eval_aui_005fscript_005f0 = _jspx_th_aui_005fscript_005f0.doStartTag();
        if (_jspx_eval_aui_005fscript_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          if (_jspx_eval_aui_005fscript_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_aui_005fscript_005f0);
          }
          do {
            out.write("\n");
            out.write("		(function() {\n");
            out.write("			var form = document.");
            out.print( namespace + formName );
            out.write(";\n");
            out.write("\n");
            out.write("			var checkbox = document.getElementById('");
            out.print( namespace + randomNamespace + dateTogglerCheckboxName );
            out.write("');\n");
            out.write("\n");
            out.write("			if (checkbox) {\n");
            out.write("				checkbox.addEventListener(\n");
            out.write("					'click',\n");
            out.write("					function() {\n");
            out.write("						var checked = checkbox.checked;\n");
            out.write("\n");
            out.write("						if (!form) {\n");
            out.write("							form = checkbox.form;\n");
            out.write("						}\n");
            out.write("\n");
            out.write("						var dayField = Liferay.Util.getFormElement(form, '");
            out.print( HtmlUtil.escapeJS(dayParam) );
            out.write("');\n");
            out.write("\n");
            out.write("						if (dayField) {\n");
            out.write("							dayField.disabled = checked;\n");
            out.write("\n");
            out.write("							if (checked) {\n");
            out.write("								dayField.value = '';\n");
            out.write("							}\n");
            out.write("						}\n");
            out.write("\n");
            out.write("						var inputDateField = Liferay.Util.getFormElement(form, '");
            out.print( HtmlUtil.getAUICompatibleId(name) );
            out.write("');\n");
            out.write("\n");
            out.write("						if (inputDateField) {\n");
            out.write("							inputDateField.disabled = checked;\n");
            out.write("\n");
            out.write("							if (checked) {\n");
            out.write("								inputDateField.value = '';\n");
            out.write("							}\n");
            out.write("						}\n");
            out.write("\n");
            out.write("						var monthField = Liferay.Util.getFormElement(form, '");
            out.print( HtmlUtil.escapeJS(monthParam) );
            out.write("');\n");
            out.write("\n");
            out.write("						if (monthField) {\n");
            out.write("							monthField.disabled = checked;\n");
            out.write("\n");
            out.write("							if (checked) {\n");
            out.write("								monthField.value = '';\n");
            out.write("							}\n");
            out.write("						}\n");
            out.write("\n");
            out.write("						var yearField = Liferay.Util.getFormElement(form, '");
            out.print( HtmlUtil.escapeJS(yearParam) );
            out.write("');\n");
            out.write("\n");
            out.write("						if (yearField) {\n");
            out.write("							yearField.disabled = checked;\n");
            out.write("\n");
            out.write("							if (checked) {\n");
            out.write("								yearField.value = '';\n");
            out.write("							}\n");
            out.write("						}\n");
            out.write("					}\n");
            out.write("				);\n");
            out.write("			}\n");
            out.write("		})();\n");
            out.write("	");
            int evalDoAfterBody = _jspx_th_aui_005fscript_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
          if (_jspx_eval_aui_005fscript_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.popBody();
          }
        }
        if (_jspx_th_aui_005fscript_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_aui_005fscript_005f0, _jsp_getInstanceManager(), false);
      }
      out.write('\n');
}
      out.write('\n');
      out.write('\n');
      //  aui:script
      com.liferay.taglib.aui.ScriptTag _jspx_th_aui_005fscript_005f1 = new com.liferay.taglib.aui.ScriptTag();
      _jsp_getInstanceManager().newInstance(_jspx_th_aui_005fscript_005f1);
      try {
        _jspx_th_aui_005fscript_005f1.setPageContext(_jspx_page_context);
        _jspx_th_aui_005fscript_005f1.setParent(null);
        // /html/taglib/ui/input_date/page.jsp(240,0) name = use type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_aui_005fscript_005f1.setUse( "aui-datepicker" + (BrowserSnifferUtil.isMobile(request) ? "-native" : StringPool.BLANK) );
        int _jspx_eval_aui_005fscript_005f1 = _jspx_th_aui_005fscript_005f1.doStartTag();
        if (_jspx_eval_aui_005fscript_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          if (_jspx_eval_aui_005fscript_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_aui_005fscript_005f1);
          }
          do {
            out.write("\n");
            out.write("	Liferay.component(\n");
            out.write("		'");
            out.print( nameId );
            out.write("DatePicker',\n");
            out.write("		function() {\n");
            out.write("			var keysPressed = {};\n");
            out.write("\n");
            out.write("			var onKeyDown = function (domEvent) {\n");
            out.write("				if (domEvent.keyCode === 16) {\n");
            out.write("					keysPressed[domEvent.keyCode] = true;\n");
            out.write("				}\n");
            out.write("			};\n");
            out.write("\n");
            out.write("			var onKeyUp = function (domEvent) {\n");
            out.write("				if (domEvent.keyCode === 16) {\n");
            out.write("					delete keysPressed[domEvent.keyCode];\n");
            out.write("				}\n");
            out.write("			};\n");
            out.write("\n");
            out.write("			var closePopoverOnKeyboardNavigation = function (instance) {\n");
            out.write("				instance.hide();\n");
            out.write("\n");
            out.write("				keysPressed = {};\n");
            out.write("\n");
            out.write("				var trigger = A.one('#");
            out.print( nameId );
            out.write("');\n");
            out.write("\n");
            out.write("				if (trigger) {\n");
            out.write("					Liferay.Util.focusFormField(trigger);\n");
            out.write("				}\n");
            out.write("			}\n");
            out.write("\n");
            out.write("			var datePicker = new A.DatePicker");
            out.print( BrowserSnifferUtil.isMobile(request) ? "Native" : StringPool.BLANK );
            out.write("(\n");
            out.write("				{\n");
            out.write("					calendar: {\n");
            out.write("						");

						String calendarOptions = String.format("headerRenderer: '%s'", LanguageUtil.get(resourceBundle, "b-y"));

						if (lastEnabledDate != null) {
							calendarOptions += StringPool.COMMA + String.format("maximumDate: new Date(%s)", lastEnabledDate.getTime());
						}

						if (firstEnabledDate != null) {
							calendarOptions += StringPool.COMMA + String.format("minimumDate: new Date(%s)", firstEnabledDate.getTime());
						}

						if (firstDayOfWeek != -1) {
							calendarOptions += StringPool.COMMA + String.format("'strings.first_weekday': %d", firstDayOfWeek);
						}
						
            out.write("\n");
            out.write("\n");
            out.write("						");
            out.print( calendarOptions );
            out.write("\n");
            out.write("					},\n");
            out.write("					container: '#");
            out.print( randomNamespace );
            out.write("displayDate',\n");
            out.write("					mask: '");
            out.print( mask );
            out.write("',\n");
            out.write("					on: {\n");
            out.write("						destroy: function () {\n");
            out.write("							document.removeEventListener('keydown', onKeyDown);\n");
            out.write("							document.removeEventListener('keyup', onKeyUp);\n");
            out.write("						},\n");
            out.write("						disabledChange: function(event) {\n");
            out.write("							var instance = this;\n");
            out.write("\n");
            out.write("							var container = instance.get('container');\n");
            out.write("\n");
            out.write("							var newVal = event.newVal;\n");
            out.write("\n");
            out.write("							container.one('#");
            out.print( dayParamId );
            out.write("').attr('disabled', newVal);\n");
            out.write("							container.one('#");
            out.print( monthParamId );
            out.write("').attr('disabled', newVal);\n");
            out.write("							container.one('#");
            out.print( nameId );
            out.write("').attr('disabled', newVal);\n");
            out.write("							container.one('#");
            out.print( yearParamId );
            out.write("').attr('disabled', newVal);\n");
            out.write("						},\n");
            out.write("						enterKey: function() {\n");
            out.write("							var instance = this;\n");
            out.write("\n");
            out.write("							var inputVal = instance.get('activeInput').val();\n");
            out.write("\n");
            out.write("							var date = instance.getParsedDatesFromInputValue(inputVal);\n");
            out.write("\n");
            out.write("							if (date) {\n");
            out.write("								datePicker.updateValue(date[0]);\n");
            out.write("							}\n");
            out.write("							else if (");
            out.print( nullable );
            out.write(" && !date) {\n");
            out.write("								datePicker.updateValue('');\n");
            out.write("							}\n");
            out.write("\n");
            out.write("							var countInterval = 0;\n");
            out.write("\n");
            out.write("							var intervalId = setInterval(function () {\n");
            out.write("								var trigger = A.one('.datepicker-popover:not(.popover-hidden) .yui3-calendarnav-prevmonth');\n");
            out.write("\n");
            out.write("								if (trigger) {\n");
            out.write("									Liferay.Util.focusFormField(trigger);\n");
            out.write("									clearInterval(intervalId);\n");
            out.write("								} else if (countInterval > 10) {\n");
            out.write("									clearInterval(intervalId);\n");
            out.write("								}\n");
            out.write("\n");
            out.write("								countInterval++;\n");
            out.write("							}, 100);\n");
            out.write("						},\n");
            out.write("						init: function () {\n");
            out.write("							document.addEventListener('keydown', onKeyDown);\n");
            out.write("							document.addEventListener('keyup', onKeyUp);\n");
            out.write("						},\n");
            out.write("						selectionChange: function(event) {\n");
            out.write("							var newSelection = event.newSelection[0];\n");
            out.write("\n");
            out.write("							var nullable = ");
            out.print( nullable );
            out.write(";\n");
            out.write("\n");
            out.write("							var date = A.DataType.Date.parse(newSelection);\n");
            out.write("							var invalidNumber = isNaN(newSelection);\n");
            out.write("\n");
            out.write("							if ((invalidNumber && !nullable) || (invalidNumber && !date && nullable && newSelection) || (newSelection.getFullYear() > 9999)) {\n");
            out.write("								event.newSelection[0] = new Date();\n");
            out.write("\n");
            out.write("								const instance = this;\n");
            out.write("\n");
            out.write("								const container = instance.get('container');\n");
            out.write("\n");
            out.write("								let year = container.one('#");
            out.print( yearParamId );
            out.write("');\n");
            out.write("\n");
            out.write("								const fullYear = newSelection.getFullYear();\n");
            out.write("\n");
            out.write("								year.val(fullYear);\n");
            out.write("\n");
            out.write("								const parentNode = A.one('#");
            out.print( nameId );
            out.write("')._node.parentElement;\n");
            out.write("\n");
            out.write("								const feedbackElement = parentNode.querySelector('.form-feedback-item');\n");
            out.write("\n");
            out.write("								if (!feedbackElement) {\n");
            out.write("									let input = A.one('#");
            out.print( nameId );
            out.write("');\n");
            out.write("\n");
            out.write("									let changeAlert = document.createElement('div');\n");
            out.write("									let feedback = document.createElement('span');\n");
            out.write("									let sr = document.createElement('span');\n");
            out.write("\n");
            out.write("									changeAlert.className = 'form-feedback-item';\n");
            out.write("									changeAlert.role = 'alert';\n");
            out.write("									feedback.className = 'form-feedback-indicator';\n");
            out.write("									feedback.innerHTML = 'The Date has been corrected.';\n");
            out.write("									sr.className = 'sr-only'\n");
            out.write("									sr.className = 'New Date: ' + event.newSelection[0];\n");
            out.write("\n");
            out.write("									changeAlert.append(feedback);\n");
            out.write("									changeAlert.append(sr);\n");
            out.write("									input._node.insertAdjacentElement('afterEnd', changeAlert);\n");
            out.write("								}\n");
            out.write("							}\n");
            out.write("\n");
            out.write("							var updatedVal = '';\n");
            out.write("\n");
            out.write("							if (event.newSelection[0]) {\n");
            out.write("								updatedVal = event.newSelection[0];\n");
            out.write("							}\n");
            out.write("\n");
            out.write("							datePicker.updateValue(updatedVal);\n");
            out.write("						}\n");
            out.write("					},\n");
            out.write("					popover: {\n");
            out.write("						on: {\n");
            out.write("							keydown: function(event) {\n");
            out.write("								var instance = this;\n");
            out.write("\n");
            out.write("								var domEvent = event.domEvent;\n");
            out.write("\n");
            out.write("								keysPressed[domEvent.keyCode] = true;\n");
            out.write("\n");
            out.write("								var isTabPressed = domEvent.keyCode === 9 || keysPressed[9];\n");
            out.write("\n");
            out.write("								var isShiftPressed = domEvent.keyCode === 16 || keysPressed[16];\n");
            out.write("\n");
            out.write("								var isForwardNavigation = isTabPressed && !isShiftPressed;\n");
            out.write("\n");
            out.write("								var isEscapePressed = domEvent.keyCode === 27 || keysPressed[27];\n");
            out.write("\n");
            out.write("								var hasClassName = domEvent.target.hasClass('yui3-calendar-grid') ||\n");
            out.write("								domEvent.target.hasClass('yui3-calendar-day');\n");
            out.write("\n");
            out.write("								if ((isForwardNavigation && hasClassName) || isEscapePressed) {\n");
            out.write("									closePopoverOnKeyboardNavigation(instance);\n");
            out.write("								}\n");
            out.write("							},\n");
            out.write("							keyup: function(event) {\n");
            out.write("								var instance = this;\n");
            out.write("\n");
            out.write("								var domEvent = event.domEvent;\n");
            out.write("\n");
            out.write("								var isTabPressed = domEvent.keyCode === 9 || keysPressed[9];\n");
            out.write("\n");
            out.write("								var isShiftPressed = domEvent.keyCode === 16 || keysPressed[16];\n");
            out.write("\n");
            out.write("								var isBackwardNavigation = isTabPressed && isShiftPressed;\n");
            out.write("\n");
            out.write("								var hasClassName = domEvent.target.hasClass('yui3-calendar-focused');\n");
            out.write("\n");
            out.write("								if (isBackwardNavigation && hasClassName) {\n");
            out.write("									closePopoverOnKeyboardNavigation(instance);\n");
            out.write("								}\n");
            out.write("\n");
            out.write("								delete keysPressed[domEvent.keyCode];\n");
            out.write("							}\n");
            out.write("						},\n");
            out.write("						zIndex: Liferay.zIndex.POPOVER\n");
            out.write("					},\n");
            out.write("					trigger: '#");
            out.print( nameId );
            out.write("'\n");
            out.write("				}\n");
            out.write("			);\n");
            out.write("\n");
            out.write("			datePicker.getDate = function() {\n");
            out.write("				var instance = this;\n");
            out.write("\n");
            out.write("				var container = instance.get('container');\n");
            out.write("\n");
            out.write("				return new Date(container.one('#");
            out.print( yearParamId );
            out.write("').val(), container.one('#");
            out.print( monthParamId );
            out.write("').val(), container.one('#");
            out.print( dayParamId );
            out.write("').val());\n");
            out.write("			};\n");
            out.write("\n");
            out.write("			datePicker.updateValue = function(date) {\n");
            out.write("				const instance = this;\n");
            out.write("\n");
            out.write("				const container = instance.get('container');\n");
            out.write("\n");
            out.write("				let dateVal = '';\n");
            out.write("				let monthVal = '';\n");
            out.write("				let yearVal = '';\n");
            out.write("\n");
            out.write("				if (date && !isNaN(date)) {\n");
            out.write("					dateVal = date.getDate();\n");
            out.write("					monthVal = date.getMonth();\n");
            out.write("					yearVal = date.getFullYear();\n");
            out.write("				}\n");
            out.write("\n");
            out.write("				let day = container.one('#");
            out.print( dayParamId );
            out.write("');\n");
            out.write("				let month = container.one('#");
            out.print( monthParamId );
            out.write("');\n");
            out.write("				let year = container.one('#");
            out.print( yearParamId );
            out.write("');\n");
            out.write("\n");
            out.write("				if (!(yearVal < 9999 && year._node.value > 9999)) {\n");
            out.write("					if (day._node.value != dateVal || month._node.value != monthVal || year._node.value !=yearVal) {\n");
            out.write("						const parentNode = A.one('#");
            out.print( nameId );
            out.write("')._node.parentElement;\n");
            out.write("\n");
            out.write("						const feedbackElement = parentNode.querySelector('.form-feedback-item');\n");
            out.write("\n");
            out.write("						if (feedbackElement) {\n");
            out.write("							parentNode.removeChild(feedbackElement);\n");
            out.write("						}\n");
            out.write("					}\n");
            out.write("				}\n");
            out.write("\n");
            out.write("				day.val(dateVal);\n");
            out.write("				month.val(monthVal);\n");
            out.write("				year.val(yearVal);\n");
            out.write("			};\n");
            out.write("\n");
            out.write("			datePicker.after(\n");
            out.write("				'selectionChange',\n");
            out.write("				function() {\n");
            out.write("					var input = A.one('#");
            out.print( nameId );
            out.write("');\n");
            out.write("\n");
            out.write("					if (input) {\n");
            out.write("						var form = input.get('form');\n");
            out.write("\n");
            out.write("						var formId = form.get('id');\n");
            out.write("\n");
            out.write("						var formInstance = Liferay.Form.get(formId);\n");
            out.write("\n");
            out.write("						if (formInstance && formInstance.formValidator) {\n");
            out.write("							formInstance.formValidator.validateField('");
            out.print( namespace + HtmlUtil.escape(name) );
            out.write("');\n");
            out.write("						}\n");
            out.write("					}\n");
            out.write("				}\n");
            out.write("			);\n");
            out.write("\n");
            out.write("			Liferay.once(\n");
            out.write("				'screenLoad',\n");
            out.write("				function() {\n");
            out.write("					datePicker.destroy();\n");
            out.write("				}\n");
            out.write("			);\n");
            out.write("\n");
            out.write("			return datePicker;\n");
            out.write("		}\n");
            out.write("	);\n");
            out.write("\n");
            out.write("	Liferay.component('");
            out.print( nameId );
            out.write("DatePicker');\n");
            int evalDoAfterBody = _jspx_th_aui_005fscript_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
          if (_jspx_eval_aui_005fscript_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.popBody();
          }
        }
        if (_jspx_th_aui_005fscript_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_aui_005fscript_005f1, _jsp_getInstanceManager(), false);
      }
      out.write('\n');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
